GET  http://localhost:3001/api/blogs
Content-Type: application/json

{}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "testing deletion",
    "author": "Deez John",
    "url": "thirdissue"
}

###
DELETE  http://localhost:3001/api/blogs/6a3651a599233f6926ed5b1c
Content-Type: application/json

{}

###
PUT http://localhost:3001/api/blogs/6a2ea382c688ac995375cfa5
Content-Type: application/json

{
    "likes": 15,
    "id": "6a2ea382c688ac995375cfa5"
}

### 
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "firstUser",
    "name": "Hallo",
    "password": "salainen"
}

### 
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "second",
    "name": "Hallo",
    "password": "salainen"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Testing author display",
    "author": "Deez John",
    "url": "issue"
}