POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Initial testing",
    "author": "John Deez",
    "url": "firstissue",
    "likes": 2
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Third testing",
    "author": "Deez John",
    "url": "thirdissue",
    "likes": 20
}